exp_id: 2026-05-21_e5r-llama32-1b-instruct-gsm8k-100-2048-metriconly
seed: 42

model:
  name: LLM-Research/Llama-3.2-1B-Instruct
  source: modelscope
  dtype: bfloat16
  device: cuda:1

dataset:
  name: gsm8k
  source: oss
  split: test
  n_samples: 100

extraction:
  max_new_tokens: 2048
