#!/usr/bin/env bash
# Re-run the Qwen-Instruct steering validation family under the corrected EOS
# envelope, then re-freeze selection and run one locked confirmation per
# eligible method.
#
# Context: the v1 validation/locked family was generated by a runner that
# overrode the model's multi-EOS set with tokenizer.eos_token_id, forcing every
# completion to max_new_tokens.  The runner is fixed (EXECUTION_LOG entry
# 2026-08-04 "Qwen steering evaluation EOS override defect").  This chain uses
# fresh v2 output directories; the layer/alpha grid, method family, vector
# registries, calibration runs, splits, and evaluation rule are unchanged.
set -euo pipefail

REPO=${REPO:-/root/AI/geoprobe-tacl-revision}
RUNS_ROOT=${RUNS_ROOT:-/root/AI/runs}
PY=${PY:-/root/miniconda3/envs/geoprobe/bin/python}
MODEL=${MODEL:-/root/.cache/modelscope/hub/models/Qwen/Qwen2.5-1.5B-Instruct}
MODEL_SOURCE=${MODEL_SOURCE:-huggingface}
MAX_NEW_TOKENS=${MAX_NEW_TOKENS:-512}

ROOT="$RUNS_ROOT/tacl-revision"
CHAIN_DIR="$ROOT/qwen-validation-v2-chain"
SELECTION="$ROOT/selection-qwen-instruct-v2.json"
LOCKED_ROOT="$ROOT/locked-gsm8k-qwen-instruct-v2"
REPORT_ROOT="$ROOT/locked-report-qwen-instruct-v2"
# CAA/ActAdd/coordinate-sparse/SAE are source-trained controls.  Their v1
# contrast pool was generated with the same single-EOS defect as the v1 grid,
# so the complete v2 family must rebuild these vectors before they can enter a
# fair comparison.  CrossSteer/target-calibrated vectors come from the audited
# extraction path and are not regenerated here.
CONTRAST_POOL="$RUNS_ROOT/revision_gsm8k_qwen_instruct_caa_source_k4_v2"
CONTRAST_REGISTRY="$ROOT/prompt-contrast-registry-gsm8k-ids0-99-v2"
SAE_REGISTRY="$ROOT/sae-sparse-registry-qwen-gsm8k-ids0-99-v2"
TARGET_CALIBRATION="$ROOT/revision_gsm8k_qwen_instruct_calibration_100"
mkdir -p "$CHAIN_DIR"

log() { printf '%s %s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$*" | tee -a "$CHAIN_DIR/chain.log"; }
fail() {
  local message=$1
  printf '%s\n' "$message" >"$CHAIN_DIR/FAILURE_REASON"
  log "FAILED: $message"
  exit 1
}
trap 'rc=$?; if [[ $rc -ne 0 && ! -f "$CHAIN_DIR/FAILURE_REASON" ]]; then printf "unexpected v2 validation-chain failure (exit=%s)\n" "$rc" >"$CHAIN_DIR/FAILURE_REASON"; fi' EXIT
wait_done() {
  local path=$1
  while [[ ! -f "$path/DONE" ]]; do
    [[ -f "$path/FAILURE_REASON" ]] && fail "dependency failed: $path"
    sleep 60
  done
}
wait_gpu_free() {
  # The two stale v1 locked jobs (sae/negative) still occupy the GPUs; wait for
  # every compute process to exit before starting the v2 family.
  local waited=0
  while :; do
    local n
    n=$(nvidia-smi --query-compute-apps=pid --format=csv,noheader 2>/dev/null | grep -c . || true)
    if [[ "$n" -eq 0 ]]; then
      log "both GPUs free"
      return 0
    fi
    waited=$((waited + 60))
    if [[ $waited -gt 3600 ]]; then
      fail "waited 60m for a free GPU"
    fi
    sleep 60
  done
}
run_grid() {
  local method=$1 vector=$2 device=$3 out=$4
  mkdir -p "$out"
  log "starting v2 $method on $device"
  "$PY" -u scripts/revision_steering_validation_grid.py \
    --vector "$method=$vector" \
    --target-model "$MODEL" --target-source "$MODEL_SOURCE" --target-device "$device" \
    --eval-start 100 --eval-count 100 \
    --layers 8,14,20,24 --alphas 0.025,0.05,0.10,0.20 \
    --schedule constant --injection-mode absolute --max-new-tokens "$MAX_NEW_TOKENS" \
    --out "$out" >"$out/run.log" 2>&1 &
  echo $! >"$out/PID"
}
run_step() {
  local name=$1
  shift
  log "starting $name"
  if ! "$@" >"$CHAIN_DIR/$name.log" 2>&1; then
    fail "$name failed; see $CHAIN_DIR/$name.log"
  fi
}

cd "$REPO"
export PYTHONPATH="$REPO/src${PYTHONPATH:+:$PYTHONPATH}"
export GEOPROBE_RUNS="$RUNS_ROOT"

wait_gpu_free

prepare_eos_corrected_baselines() {
  if [[ ! -f "$CONTRAST_POOL/DONE" ]]; then
    run_step generate-eos-corrected-contrast-pool "$PY" -u scripts/revision_generate_contrast_pool.py \
      --config configs/revision_gsm8k_qwen_instruct_caa_source_k4_v2.yaml
  fi
  [[ -f "$CONTRAST_POOL/DONE" ]] || fail "v2 contrast pool is incomplete"

  if [[ ! -f "$CONTRAST_REGISTRY/manifest.json" ]]; then
    run_step build-eos-corrected-prompt-registry "$PY" -u scripts/revision_build_prompt_contrast_registry.py \
      --target-run "$CONTRAST_POOL" --model "$MODEL" --model-source "$MODEL_SOURCE" \
      --device cuda:0 --out "$CONTRAST_REGISTRY"
  fi
  [[ -f "$CONTRAST_REGISTRY/manifest.json" ]] || fail "v2 prompt contrast registry is missing"

  if [[ ! -f "$SAE_REGISTRY/manifest.json" ]]; then
    run_step build-eos-corrected-sae-registry "$PY" -u scripts/revision_build_sae_sparse_registry.py \
      --calibration-run "$TARGET_CALIBRATION" --contrast-run "$CONTRAST_POOL" \
      --model "$MODEL" --model-source "$MODEL_SOURCE" --device cuda:0 --out "$SAE_REGISTRY"
  fi
  [[ -f "$SAE_REGISTRY/manifest.json" ]] || fail "v2 SAE registry is missing"
}

# Never compare a fixed CrossSteer vector to CAA/ActAdd/SAE controls whose
# source generations were decoded under a different EOS envelope.
prepare_eos_corrected_baselines

declare -A VECTORS=(
  [crosssteer_source]="$ROOT/vector-registry-gsm8k-ids0-99/crosssteer_source.pt"
  [target_calibrated]="$ROOT/vector-registry-gsm8k-ids0-99/target_calibrated.pt"
  [caa_target_prompt_final]="$CONTRAST_REGISTRY/caa_target_prompt_final.pt"
  [actadd_target_prompt_final]="$CONTRAST_REGISTRY/actadd_target_prompt_final.pt"
  [sparse_caa_coordinate_10pct]="$CONTRAST_REGISTRY/sparse_caa_coordinate_10pct.pt"
  [matched_norm_random]="$ROOT/matched-random-registry-qwen-gsm8k-ids0-99/matched_norm_random.pt"
  [negative_crosssteer_source]="$ROOT/negative-direction-registry-qwen-gsm8k-ids0-99/negative_crosssteer_source.pt"
  [sae_sparse_activation]="$SAE_REGISTRY/sae_sparse_activation.pt"
)
for method in crosssteer_source target_calibrated caa_target_prompt_final actadd_target_prompt_final; do
  [[ -f "${VECTORS[$method]}" ]] || fail "missing vector for $method"
done
log "all eight v2 vectors present"

# Launch the eight validation grids two at a time (one per GPU).
ORDER=(crosssteer_source target_calibrated caa_target_prompt_final actadd_target_prompt_final \
       matched_norm_random negative_crosssteer_source sae_sparse_activation sparse_caa_coordinate_10pct)
GRID_DIRS=()
i=0
while (( i < ${#ORDER[@]} )); do
  a=${ORDER[$i]}; b=${ORDER[$((i + 1))]}
  out_a="$ROOT/validation-grid-v2-$a"; out_b="$ROOT/validation-grid-v2-$b"
  GRID_DIRS+=("$out_a" "$out_b")
  if [[ -f "$out_a/DONE" && -f "$out_b/DONE" ]]; then
    log "grid pair ($a,$b) already complete"
  else
    run_grid "$a" "${VECTORS[$a]}" cuda:0 "$out_a"
    run_grid "$b" "${VECTORS[$b]}" cuda:1 "$out_b"
    wait "$(cat "$out_a/PID")" || fail "grid failed: $a"
    wait "$(cat "$out_b/PID")" || fail "grid failed: $b"
  fi
  i=$((i + 2))
done
for d in "${GRID_DIRS[@]}"; do
  [[ -f "$d/DONE" ]] || fail "validation grid incomplete: $d"
done
log "all eight v2 validation grids complete"

# Freeze selection from the v2 family (audits shared baselines and manifests).
if [[ ! -f "$SELECTION" ]]; then
  run_step freeze-selection "$PY" -u scripts/revision_select_validation.py \
    --run "crosssteer_source=$ROOT/validation-grid-v2-crosssteer_source" \
    --run "target_calibrated=$ROOT/validation-grid-v2-target_calibrated" \
    --run "caa_target_prompt_final=$ROOT/validation-grid-v2-caa_target_prompt_final" \
    --run "actadd_target_prompt_final=$ROOT/validation-grid-v2-actadd_target_prompt_final" \
    --run "sparse_caa_coordinate_10pct=$ROOT/validation-grid-v2-sparse_caa_coordinate_10pct" \
    --run "matched_norm_random=$ROOT/validation-grid-v2-matched_norm_random" \
    --run "sae_sparse_activation=$ROOT/validation-grid-v2-sae_sparse_activation" \
    --run "negative_crosssteer_source=$ROOT/validation-grid-v2-negative_crosssteer_source" \
    --out "$SELECTION"
fi
[[ -f "$SELECTION" ]] || fail "v2 selection artifact is missing"

# One locked run per eligible method on GSM8K IDs 200--299.
mapfile -t METHODS < <("$PY" - "$SELECTION" <<'PY'
import json, sys
for item in json.load(open(sys.argv[1]))["methods"]:
    if item["decision"].get("eligible"):
        print(item["method"])
PY
)
if [[ ${#METHODS[@]} -eq 0 ]]; then
  log "v2 selection has no behavior-eligible Qwen method; locked test is prohibited"
  mkdir -p "$LOCKED_ROOT" "$REPORT_ROOT"
  touch "$LOCKED_ROOT/NO_ELIGIBLE_METHODS"
  touch "$CHAIN_DIR/DONE"
  exit 0
fi

mkdir -p "$LOCKED_ROOT" "$REPORT_ROOT"
log "launching one locked Qwen run for every v2-eligible method: ${METHODS[*]}"
PIDS=()
idx=0
for method in "${METHODS[@]}"; do
  out="$LOCKED_ROOT/$method"
  if [[ -f "$out/DONE" ]]; then
    continue
  fi
  device="cuda:$((idx % 2))"
  mkdir -p "$out"
  "$PY" -u scripts/revision_launch_locked_selected.py \
    --selection "$SELECTION" --method "$method" \
    --target-model "$MODEL" --target-source "$MODEL_SOURCE" --target-device "$device" \
    --out "$out" --execute >"$out/run.log" 2>&1 &
  PIDS+=("$!")
  idx=$((idx + 1))
  if [[ ${#PIDS[@]} -eq 2 ]]; then
    wait "${PIDS[0]}" || fail "one v2 locked method process failed"
    wait "${PIDS[1]}" || fail "one v2 locked method process failed"
    PIDS=()
  fi
done
for pid in "${PIDS[@]}"; do
  wait "$pid" || fail "one v2 locked method process failed"
done
for method in "${METHODS[@]}"; do
  [[ -f "$LOCKED_ROOT/$method/DONE" ]] || fail "v2 locked run incomplete: $method"
done

REPORT_ARGS=(--selection "$SELECTION" --out "$REPORT_ROOT")
for method in "${METHODS[@]}"; do REPORT_ARGS+=(--run "$method=$LOCKED_ROOT/$method"); done
run_step build-locked-report "$PY" -u scripts/revision_build_locked_report.py "${REPORT_ARGS[@]}"
[[ -f "$REPORT_ROOT/locked_report_manifest.json" ]] || fail "complete v2 locked report is missing"

touch "$CHAIN_DIR/DONE"
log "v2 validation + selection + locked chain complete"
