#!/usr/bin/env bash
# One-time environment setup for the geoprobe project.
# Idempotent — safe to re-run.
#
# What this does:
#   1. Create conda env "geoprobe" (Python 3.10) if missing
#   2. Set up external storage dirs (~/AI/cache, ~/AI/runs)
#   3. Wire env vars into the conda env's activate hook
#   4. Install the package (editable) + torch extras
#
# Geometric extras ([geo]) are NOT installed here — install them per-phase
# (see docs/research_plan.md) to keep the env small and stable.

set -euo pipefail

ENV_NAME="geoprobe"
PY_VERSION="3.10"
PROJ_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

echo "==> Project root: $PROJ_ROOT"

# 1. conda env
if ! conda env list | awk '{print $1}' | grep -qx "$ENV_NAME"; then
    echo "==> Creating conda env: $ENV_NAME (python=$PY_VERSION) from conda-forge"
    # conda-forge avoids the Anaconda repo ToS prompt and is the community standard.
    conda create -y -n "$ENV_NAME" --override-channels -c conda-forge "python=$PY_VERSION"
else
    echo "==> conda env $ENV_NAME already exists, skipping create"
fi

# 2a. git safe.directory (容器/挂载 uid 不一致时必需 — 见 lessons_learned)
if git -C "$PROJ_ROOT" rev-parse 2>/dev/null; then
    git config --global --add safe.directory "$PROJ_ROOT" 2>/dev/null || true
fi

# 2. external dirs
echo "==> Ensuring external storage dirs"
mkdir -p "$HOME/AI/cache/huggingface"
mkdir -p "$HOME/AI/cache/huggingface/datasets"
mkdir -p "$HOME/AI/cache/huggingface/transformers"
mkdir -p "$HOME/AI/cache/torch"
mkdir -p "$HOME/AI/runs"

# 3. activate hook — exports the env vars whenever you `conda activate geoprobe`
ENV_PREFIX="$(conda env list | awk -v n="$ENV_NAME" '$1==n {print $NF}')"
HOOK_DIR="$ENV_PREFIX/etc/conda/activate.d"
mkdir -p "$HOOK_DIR"
cat > "$HOOK_DIR/geoprobe.sh" <<EOF
# Auto-generated by scripts/setup_env.sh — do not edit by hand.
export GEOPROBE_HOME="$PROJ_ROOT"
export GEOPROBE_CACHE="\$HOME/AI/cache"
export GEOPROBE_RUNS="\$HOME/AI/runs"
export HF_HOME="\$GEOPROBE_CACHE/huggingface"
export HF_DATASETS_CACHE="\$GEOPROBE_CACHE/huggingface/datasets"
export TRANSFORMERS_CACHE="\$GEOPROBE_CACHE/huggingface/transformers"
export TORCH_HOME="\$GEOPROBE_CACHE/torch"
EOF
echo "==> Wrote activate hook: $HOOK_DIR/geoprobe.sh"

# 4. install package (in the geoprobe env, NOT in base)
echo "==> Installing geoprobe (editable) + torch extras into env $ENV_NAME"
# shellcheck source=/dev/null
source "$(conda info --base)/etc/profile.d/conda.sh"
conda activate "$ENV_NAME"
pip install --upgrade pip
pip install -e "$PROJ_ROOT[torch,dev]"
# 5. import smoke test — catch missing transitive deps early
echo "==> Smoke test: import critical modules"
python - <<'PYEOF'
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer  # noqa: F401
from modelscope import snapshot_download  # noqa: F401
from modelscope.msdatasets import MsDataset  # noqa: F401
print(f"OK — torch {torch.__version__}, cuda={torch.cuda.is_available()}, devices={torch.cuda.device_count()}")
PYEOF

conda deactivate

cat <<EOF

==> Done.

Next steps:
    conda activate $ENV_NAME
    python -c "import torch; print('CUDA available:', torch.cuda.is_available(), 'devices:', torch.cuda.device_count())"

When entering Phase 2 (geometric metrics), additionally run:
    pip install -e "$PROJ_ROOT[geo]"
EOF
